name: LeetCode Sync

on:
  workflow_dispatch: {}   # allows manual trigger

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Configure git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ secrets.MY_GH_EMAIL }}"

      - name: Run sync script (force backfill, credited to you)
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          AUTHOR_NAME: ${{ github.actor }}
          AUTHOR_EMAIL: ${{ secrets.MY_GH_EMAIL }}
          FORCE_RECOMMIT: "1"                # backfill forced commits
          REPO_PATH: ${{ github.workspace }}
          BRANCH: main
        run: python leetcode_sync.py

      - name: Show last 20 commits (debug)
        run: |
          git --no-pager log -n 20 --pretty=format:"%h | %an <%ae> | %ad | %s"
