name: LeetCode Sync (robust)

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run leetcode sync
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          REPO_PATH: ${{ github.workspace }}
          BRANCH: ${{ github.ref_name }}
        run: |
          python leetcode_sync.py
